Leaderboard: hit the API 🎯
ritikarawat220/LEADERBOARD- pull request #2
Opened 2023-03-15 14:15 UTC by ritikarawat220

### Send and receive data from API

- [x]     Add _getScores_ and _postScores_ functions.
- [x]     Implement the _"Refresh"_ button.
- [x]     Implement the form "_Submit_" button.

2023-03-15 14:55 UTC, Olamarx requested changes
Hi @ritikarawat220, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights
- Linters passed ✔️
- Readme file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 14:55 UTC, Olamarx commented on src/request.js
> +  };
- [ ] I see you are not using the id parameter, it is best practice to remove it. I removed it and it still works fine.

2023-03-15 14:55 UTC, Olamarx commented on src/request.js
> +  const postScores = async (id, body) => {
- [ ] Same thing applies to this id.

2023-03-15 14:55 UTC, Olamarx commented on src/index.js
> +  itemList(scores.result);
- [ ] It is of best practice to destructure your data for easy usage just as I did in the attached image.
![image](https://user-images.githubusercontent.com/86200356/225347405-f5d79022-5dac-4cad-92b5-50d8b14c7c3e.png)

2023-03-15 14:55 UTC, Olamarx commented on src/index.js
> +  getScores(TEST_GAME_ID).then((scores) => {
- [ ] Don't forget to remove the parameter in the getScores.

2023-03-15 15:22 UTC, frank1738 approved these changes
Hi @ritikarawat220 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ Good documentation👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 15:24 UTC, ritikarawat220 commented on src/index.js
> +  itemList(scores.result);
thankyou for giving good suggestions. 😄

2023-03-15 15:30 UTC, merged

2023-04-18 06:21 UTC, ritikarawat220 commented
Thanks for Approving! 😄